app = "deploy-frontend-geolocalizacion"
primary_region = "gru"

[build]
  dockerfile = "dockerfile"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 1

[[http_service.checks]]
  interval = "10s"
  timeout = "2s"
  method = "get"
  path = "/"
  protocol = "http"
