name: Deploy to Fly.io

on:
  push:
    branches:
      - main
    paths-ignore:
      - 'README.md'
      - 'LICENSE'
      - '.gitignore'
      - '**/*.md'

jobs:
  deploy:
    name: Deploy app
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Force install dependencies
        run: npm install --force

      - name: Build project
        run: npm run build

      - name: Install Fly.io CLI
        run: curl -L https://fly.io/install.sh | sh

      - name: Add Fly.io to PATH
        run: echo "$HOME/.fly/bin" >> $GITHUB_PATH

      - name: Set secrets on Fly.io
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
          NEXT_PUBLIC_GOOGLE_MAPS_API_KEY: ${{ secrets.NEXT_PUBLIC_GOOGLE_MAPS_API_KEY }}
          NEXT_PUBLIC_API_URL_BACK: ${{ secrets.NEXT_PUBLIC_API_URL_BACK }}
          NEXT_PUBLIC_WEB_SOCKET_URL_CLOUD: ${{ secrets.NEXT_PUBLIC_WEB_SOCKET_URL_CLOUD }}
        run: |
          flyctl secrets set \
            NEXT_PUBLIC_GOOGLE_MAPS_API_KEY="$NEXT_PUBLIC_GOOGLE_MAPS_API_KEY" \
            NEXT_PUBLIC_API_URL_BACK="$NEXT_PUBLIC_API_URL_BACK" \
            NEXT_PUBLIC_WEB_SOCKET_URL_CLOUD="$NEXT_PUBLIC_WEB_SOCKET_URL_CLOUD"

      - name: Deploy to Fly.io
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
        run: |
          flyctl deploy --remote-only
